In [1]:
import numpy as np

In [180]:
image_height = 6
image_width = 1

No_of_Images = 4
No_of_Classes = 4

y_true = [2,3,1,0]

W = np.random.rand(No_of_Classes*image_height*image_width).reshape(No_of_Classes,image_height*image_width)*10
X = np.random.rand(No_of_Images*image_height*image_width).reshape(image_height*image_width, No_of_Images)

In [181]:
for i in range(W.shape[0]):
    for j in range(W.shape[1]):
        print(i,j)

0 0
0 1
0 2
0 3
0 4
0 5
1 0
1 1
1 2
1 3
1 4
1 5
2 0
2 1
2 2
2 3
2 4
2 5
3 0
3 1
3 2
3 3
3 4
3 5


In [182]:
W.shape

(4, 6)

In [183]:
X.shape

(6, 4)

In [184]:
X[1][0]

0.5488748210479546

In [185]:
P = np.matmul(W, X)

In [201]:
W

array([[9.95266333, 4.70195716, 9.21648729, 5.18106776, 3.92203657,
        6.17241652],
       [9.4062048 , 2.13348788, 4.73210379, 8.51815707, 2.98791401,
        7.76938803],
       [3.94623903, 5.61405192, 4.23200054, 1.65196393, 2.21780173,
        5.16147488],
       [8.12915942, 8.53646767, 9.88932961, 3.0614536 , 9.58208386,
        2.07559315]])

In [202]:
X

array([[0.91292529, 0.95638748, 0.55902256, 0.06186809],
       [0.54887482, 0.57192509, 0.62314787, 0.59728088],
       [0.76434295, 0.74303668, 0.15322901, 0.82876717],
       [0.11275412, 0.3073935 , 0.00525557, 0.63861009],
       [0.3428857 , 0.80832304, 0.23525267, 0.80640164],
       [0.62596816, 0.41392853, 0.37667139, 0.15531987]])

In [200]:
P

array([[24.50411422, 26.37379641, 13.18088295, 18.49258127],
       [20.22349002, 21.98189568, 10.98704346, 14.83402786],
       [14.09637009, 14.5664673 ,  8.82749215, 10.74973464],
       [24.59561302, 29.55061835, 14.43131447, 23.80202035]])

In [186]:
W.shape

(4, 6)

In [216]:
len(y_true)

4

In [217]:
dW = np.zeros(No_of_Classes*image_height*image_width).reshape(No_of_Classes,image_height*image_width)

for i in range(W.shape[0]):
    for j in range(W.shape[1]):
        for k in range(len(y_true)):   
#             print(i,j,k)
            print(i, j)
            print('What image are we looking at: ', k)
            print('true class: ', y_true[k])
            input('Press Enter ...')
            if y_true[k] != i:
                if P[i][k] - P[y_true[k]][k] > -1:
                    print('yes')
                    dW[i][j] += X[j][k]
                    print('X[%d][%d] : %f' %(j,k,X[j][k]))
            else:
                if P[i][k] - P[y_true[k]][k] > -1:
                    print('No')
                    dW[i][j] -= X[j][k]
                    print('X[%d][%d] : %f' %(j,k,X[j][k]))
                
#                 if P[][k]

0 0
What image are we looking at:  0
true class:  2
Press Enter ...
yes
X[0][0] : 0.912925
0 0
What image are we looking at:  1
true class:  3
Press Enter ...
0 0
What image are we looking at:  2
true class:  1
Press Enter ...
yes
X[0][2] : 0.559023
0 0
What image are we looking at:  3
true class:  0
Press Enter ...
No
X[0][3] : 0.061868
0 1
What image are we looking at:  0
true class:  2
Press Enter ...
yes
X[1][0] : 0.548875
0 1
What image are we looking at:  1
true class:  3


KeyboardInterrupt: 

In [199]:
dW

array([[ 0.51556036,  0.60009761,  0.17453527, -0.1893838 , -0.23018466,
         0.58871103],
       [-0.10533029, -0.62033115, -0.8074609 , -0.83324947, -1.27183897,
         0.05671977],
       [-1.57727813, -1.79235385, -1.72503286, -0.95125917, -1.84997735,
        -0.94591979],
       [ 1.53381594,  1.76930358,  1.74633913,  0.75661979,  1.38454001,
         1.15795942]])

In [53]:
for i in range(P.shape[0]):
    for j in range(P.shape[1]):
        print(i,j)

0 0
0 1
1 0
1 1
2 0
2 1
3 0
3 1


In [43]:
P.shape

(4, 2)