In [1]:
import numpy as np

In [48]:
image_height = 7
image_width = 2

No_of_Images = 4
No_of_Classes = 3

y_true = [2,0,1,0]

W = np.random.rand(No_of_Classes*image_height*image_width).reshape(No_of_Classes,image_height*image_width)*10
W = np.matrix.round(W)
X = np.random.rand(No_of_Images*image_height*image_width).reshape(image_height*image_width, No_of_Images)*255
X = np.matrix.round(X)

In [49]:
for i in range(W.shape[0]):
    for j in range(W.shape[1]):
        print(i,j)

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
2 12
2 13


In [50]:
W.shape

(3, 14)

In [51]:
X.shape

(14, 4)

In [52]:
X[1][0]

38.0

In [128]:
P = np.matmul(W, X)

In [129]:
X

array([[ 46., 164., 160.,  77.],
       [ 38.,  46., 193., 138.],
       [ 24., 185.,  33.,  24.],
       [225., 192.,  51., 124.],
       [143.,  35.,  32., 246.],
       [ 49., 141.,  90., 223.],
       [ 26., 179.,  40.,  64.],
       [117., 128.,  20., 181.],
       [121., 113., 226., 160.],
       [174., 154., 209., 233.],
       [ 56., 185., 197.,  52.],
       [232., 194.,  72.,   7.],
       [127.,  65., 212., 112.],
       [ 46.,  98.,  50., 141.]])

In [130]:
P

array([[ 5708., 10069.,  8370.,  8867.],
       [ 8289., 11420.,  9138.,  8794.],
       [ 6348.,  6645.,  5595.,  5814.]])

In [131]:
P[2][3] - P[0][3] + 1

-3052.0

In [132]:
P.shape

(3, 4)

In [157]:
dW = np.zeros(No_of_Classes*image_height*image_width).reshape(No_of_Classes,image_height*image_width)

DELTA = 10

P_ = np.subtract(P, np.array([[P[2][0], P[0][1], P[1][2], P[0][3]]]))

print(P_)

def myfunc(m):
    if m + DELTA>0:
        return 1.
    return 0.

vfunc = np.vectorize(myfunc)

P_ = vfunc(P_)

for i in range(len(y_true)):
    P_[y_true[i]][i] = np.nan
    
print(P_)

der_matrix = np.zeros(P_.shape[0]*P_.shape[1]).reshape(P_.shape[0], P_.shape[1])

for i in range(P.shape[0]):
    # i is the class
    for j in range(P.shape[1]):
        # j is the image number
        # if the image under consideration has the class as the class under consideration
        if np.isnan(P_[i][j]) == False:
            der_matrix[i][j] = P_[i][j]
        else:
            der_matrix[i][j] = -np.sum(P_[:,j][~np.isnan(P_[:,j])])

[[ -640.     0.  -768.     0.]
 [ 1941.  1351.     0.   -73.]
 [    0. -3424. -3543. -3053.]]
[[ 0. nan  0. nan]
 [ 1.  1. nan  0.]
 [nan  0.  0.  0.]]


In [160]:
der_matrix.shape

(3, 4)

In [162]:
np.matmul(der_matrix, X.T)

array([[-164.,  -46., -185., -192.,  -35., -141., -179., -128., -113.,
        -154., -185., -194.,  -65.,  -98.],
       [ 210.,   84.,  209.,  417.,  178.,  190.,  205.,  245.,  234.,
         328.,  241.,  426.,  192.,  144.],
       [ -46.,  -38.,  -24., -225., -143.,  -49.,  -26., -117., -121.,
        -174.,  -56., -232., -127.,  -46.]])

In [58]:
DELTA = 1
dW = np.zeros(No_of_Classes*image_height*image_width).reshape(No_of_Classes,image_height*image_width)

for i in range(W.shape[0]):
    for j in range(W.shape[1]):
        # i is the class, it will occur everywhere where class 0 is used
        for k in range(P.shape[1]):
            # k is the image we are looking at
            print(i, j)
            print('What image are we looking at: ', k)
            print('true class: ', y_true[k])
            print('Current class Prob P[%d][%d] : %f' %(i,k,P[i][k]))
            print('Actual class Prob P[%d][%d] : %f' %(y_true[k],k,P[y_true[k]][k]))
            if i != y_true[k]:
                if P[i][k] - P[y_true[k]][k] + DELTA > 0:
                    dW[i][j] += X[j][k]
            # if the image we are looking at has the same class we are curretly looping over
            if i == y_true[k]:
                for cl in range(W.shape[0]):
                    print('cl: ', cl)
                    if cl != i and P[cl][k] - P[i][k] + DELTA > 0:
                        dW[i][j] -= X[j][k]
            print('dW[%d][%d] : %f' %(i,j,dW[i][j]))
#             input('Press Enter')

0 0
What image are we looking at:  0
true class:  2
Current class Prob P[0][0] : 5708.000000
Actual class Prob P[2][0] : 6348.000000
dW[0][0] : 0.000000
0 0
What image are we looking at:  1
true class:  0
Current class Prob P[0][1] : 10069.000000
Actual class Prob P[0][1] : 10069.000000
cl:  0
cl:  1
cl:  2
dW[0][0] : -164.000000
0 0
What image are we looking at:  2
true class:  1
Current class Prob P[0][2] : 8370.000000
Actual class Prob P[1][2] : 9138.000000
dW[0][0] : -164.000000
0 0
What image are we looking at:  3
true class:  0
Current class Prob P[0][3] : 8867.000000
Actual class Prob P[0][3] : 8867.000000
cl:  0
cl:  1
cl:  2
dW[0][0] : -164.000000
0 1
What image are we looking at:  0
true class:  2
Current class Prob P[0][0] : 5708.000000
Actual class Prob P[2][0] : 6348.000000
dW[0][1] : 0.000000
0 1
What image are we looking at:  1
true class:  0
Current class Prob P[0][1] : 10069.000000
Actual class Prob P[0][1] : 10069.000000
cl:  0
cl:  1
cl:  2
dW[0][1] : -46.000000
0 1


What image are we looking at:  3
true class:  0
Current class Prob P[2][3] : 5814.000000
Actual class Prob P[0][3] : 8867.000000
dW[2][11] : -232.000000
2 12
What image are we looking at:  0
true class:  2
Current class Prob P[2][0] : 6348.000000
Actual class Prob P[2][0] : 6348.000000
cl:  0
cl:  1
cl:  2
dW[2][12] : -127.000000
2 12
What image are we looking at:  1
true class:  0
Current class Prob P[2][1] : 6645.000000
Actual class Prob P[0][1] : 10069.000000
dW[2][12] : -127.000000
2 12
What image are we looking at:  2
true class:  1
Current class Prob P[2][2] : 5595.000000
Actual class Prob P[1][2] : 9138.000000
dW[2][12] : -127.000000
2 12
What image are we looking at:  3
true class:  0
Current class Prob P[2][3] : 5814.000000
Actual class Prob P[0][3] : 8867.000000
dW[2][12] : -127.000000
2 13
What image are we looking at:  0
true class:  2
Current class Prob P[2][0] : 6348.000000
Actual class Prob P[2][0] : 6348.000000
cl:  0
cl:  1
cl:  2
dW[2][13] : -46.000000
2 13
What image

In [59]:
dW

array([[-164.,  -46., -185., -192.,  -35., -141., -179., -128., -113.,
        -154., -185., -194.,  -65.,  -98.],
       [ 210.,   84.,  209.,  417.,  178.,  190.,  205.,  245.,  234.,
         328.,  241.,  426.,  192.,  144.],
       [ -46.,  -38.,  -24., -225., -143.,  -49.,  -26., -117., -121.,
        -174.,  -56., -232., -127.,  -46.]])

In [ ]:
dW

In [ ]:
for i in range(P.shape[0]):
    for j in range(P.shape[1]):
        print(i,j)

In [ ]:
P.shape